### PR TITLE
Update contributor list

### PR DESCRIPTION
**Pull request by javier-intel**
Add Javier to Models and Tutorials SIG contributor list

### CODE REVIEW

**Review by andife — COMMENTED** [review]
You should add you also to sig leader list below

**Comment by javier-intel** [comment]
Hi Andreas, I don't see a sig leader list in the CONTRIBUTORS file, is it in a different place?

**Comment by andife** [comment]
sorry, the naming was wrong it is SIG-chairs:

SIG-chairs:
    - AlexandreEichenberger
    - gramalingam
    - jcwchen
    - kevinch-nv
    - linkerzhang
    - liqunfu
    - philass
    - postrational
    - thiagocrepaldi

**Comment by javier-intel** [comment]
Got it, thanks. How about now?

**Pull request merged**
