### PR TITLE
Update of list for SIG-Compiler

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Added the name for the sig-compiler, including all top contributors (2 or more consequential PR over last year). Approver list is longer than for other groups, and it's ok as PR get reviewed by folks all the time.

This PR started from #150

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
PS: can someone look at the list of SIG chairs? It appears to be outdated.

I added the two new one for compilers (Philip and I). I know that Ashwini is not on infra anymore, she is still listed there. 

If you post the names to add/remove on a comment, will update them accordingly.

**Comment by AlexandreEichenberger** [comment]
@prasanthpul do I need approval for this one? Or should I just merge?

**Review by andife — APPROVED** [review]
sounds good for me, but I think I don't have the rights to update the github permissions

**Comment by andife** [comment]
> PS: can someone look at the list of SIG chairs? It appears to be outdated.

maybe also WG chairs?

**Review by prasanthpul — APPROVED** [review]

**Pull request merged**
